# Generated by Django 5.0.7 on 2024-07-17 12:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idea', '0003_idea_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성일')),
                ('idea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='idea.idea', verbose_name='북마크')),
            ],
        ),
    ]
