# Generated by Django 5.0.7 on 2024-07-17 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('interest', models.IntegerField(default=0)),
                ('devtool', models.CharField(choices=[('Spring', '스프링'), ('Django', '쟝고'), ('React', '리액트'), ('Flask', '플라스크'), ('Node.Js', '노드js')], max_length=10, null=True)),
                ('img_url', models.ImageField(default='images/basic.jpg', upload_to='images/%Y%m%d')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.member', verbose_name='작성자')),
            ],
        ),
    ]
