# Generated by Django 5.0.7 on 2024-07-17 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('develop', '0001_initial'),
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='devtool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='develop.develop', verbose_name='개발툴'),
        ),
    ]
