# Generated by Django 5.0.7 on 2024-07-17 09:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_alter_idea_devtool'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성일'),
        ),
    ]
